### ISSUE TITLE
enhancement req - add masteries

### ISSUE THREAD

**Issue by gartkb** [xrandox/TehsTrails#15]
Just checking out this pack and it's really nicely done, thank you. The only thing that is obviously missing to me, is masteries. I hope you'd consider adding these! Either way, thanks for your work.

**Comment by xrandox** [comment]
I didn’t add them because they’re a one and done thing, but I’ll think about adding trails for the few that there are when I get some free time ^^

**Comment by xrandox** [comment]
No plans to add this to the current pack. I may create a standalone pack for masteries at some point, but for now, closing this issue
