### ISSUE TITLE
Trails not showing on Minimap

### ISSUE THREAD

**Issue by jreaming** [xrandox/TehsTrails#16]
![2021-04-13 10_56_03-Blish HUD](https://user-images.githubusercontent.com/666363/114574088-f0692b00-9c46-11eb-9717-f1f54f13638d.png)

As you can see above the Teh trails aren't showing up on the minimap like other waypoint packs. Tested With Tekkits and Reactif and they both show on minimap. Not sure if this is a user error or not.

**Comment by xrandox** [comment]
This is intentional...I find having the trails on minimap just adds clutter so I have them turned off — I can release a fork with them turned on if you’d prefer

**Comment by jreaming** [comment]
That would be nice, I like to be able to refer quickly to the minimap at times so I can quickly see where the trail goes next

**Comment by SaiyanOfDarkness** [comment]
> This is intentional...I find having the trails on minimap just adds clutter so I have them turned off — I can release a fork with them turned on if you’d prefer

I understand trails, but what about keeping the icons for things you need to interact with?

**Comment by jreaming** [comment]
@SaiyanOfDarkness  I'm pretty sure this is a Taco setting. If you got into keybind settings and your "action key" (Taco) is set to the same as your "interact key" (in-game), then it'll remove the marker when you go to interact with that object. I could be totally wrong on this, but I played around with it and that's how it seems to function. 

Taco menu -> GW2 Taco Settings -> Rebind Keys -> Action Key -> *Press Esc to unbind*

Hopefully that works?

**Comment by gartkb** [comment]
how I get around this is I bind a key to turn taco on or off, and that way if clutter is in the way, I just toggle.  but I do find it hard to function without being able to see the path on the map. I have seen packs that have a toggle built in for showing their paths or whatever, if another version was too much of a pain. thanks for your work on this!

**Comment by xrandox** [comment]
An optional 'minimap display option' setting has been added in the latest version for BHUD users
