### ISSUE TITLE
World Completion - Heart Related

### ISSUE THREAD

**Issue by xrandox** [xrandox/TehsTrails#2]
- [x] Add Heart Descriptions....to every heart.... :pepehands:
- [x] Add Zone - Hunting Lodge Hill - Queensdale
- [x] Add Zone - Skritt Cave Queen's Forest - Queensdale
- [x] Add Zone - Wolf Cave - Snowdens
- [x] Add Zone - Grawl Area - Snowdens
- [x] Add Zone - Spider Eggs - Plains of Ashford
- [x] Add Zone - Svanir Cliff - Wayfarer Foothills
- [x] Check if Full Inv still works in Harathi
- [x] Ettin Answers in Queensdale
- [x] Food/drink orders are not random in Lornar's, label them
- [x] Stone Trade Labels in Wayfarer
- [x] Add blurb about "Learn the way of the Kodan" - https://discordapp.com/channels/580908046364966922/698338598763626557/760545818259882044

**Comment by zotmer** [comment]
All heart related tasks completed
